---
title: "BRT Test"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

# Important note

Functions from brt.functions.R require data to be in "data.frame" format. Make sure to reclass any data using as.data.frame() before running gbm.step



```{r packages}
library(tidyverse)
library(magrittr)
library(here)

source(here("previous work", "elith_tutorial", "brt.functions.R"))
```


```{r read}
gmpd <- read_csv(here("data/GMPD_main.csv"))
panth <- read_tsv(here("data/pantheria/ECOL_90_184/PanTHERIA_1-0_WR05_Aug2008.txt"))
```

```{r NAs}
panth[panth == -999.00] <- NA

colnames(panth) <- gsub("\\d+-\\d+_", "", colnames(panth))
colnames(panth) <- gsub("*\\d+", "", colnames(panth))


panth$ref_count <- str_count(panth$References, ";")

panth$`ActivityCycle` <- as.factor(panth$`ActivityCycle`)
panth$`DietBreadth` <- as.factor(panth$`DietBreadth`)
panth$`HabitatBreadth` <- as.factor(panth$`HabitatBreadth`)
panth$`Terrestriality` <- as.factor(panth$`Terrestriality`)
panth$`TrophicLevel` <- as.factor(panth$`TrophicLevel`)

panth %<>% dplyr::select(!c(`WeaningHeadBodyLen_mm`, References, `AdultForearmLen_mm`, `AdultBodyMass_g_EXT`, `NeonateBodyMass_g_EXT`, `WeaningBodyMass_g_EXT`, MSW_Species, MSW_Genus, MSW_Family, MSW_Order, `GR_MaxLat_dd`, `GR_MinLong_dd`, `WeaningBodyMass_g`)) #too many NAs or just taxon
```


```{r psr}
gmpd_PSR <- gmpd %>% dplyr::select(HostCorrectedName,ParasiteCorrectedName) %>% 
  distinct() %>% 
  group_by(HostCorrectedName) %>% 
  summarize(psr=n())
panth %<>% mutate(HostCorrectedName = MSW_Binomial)
gmpd_panth <- gmpd_PSR %>% inner_join(panth, by="HostCorrectedName")
```



```{r partition data}
set.seed(07981)
train <- sample(1:nrow(gmpd_panth), nrow(gmpd_panth) / 2)
test <- gmpd_panth %>% mutate(row_num = rownames(.)) %>% filter(!row_num %in% train) %>% dplyr::select(row_num)
test <- as.integer(test$row_num)
gmpd_panth_train <- gmpd_panth[train,]
gmpd_panth_test <- gmpd_panth[test,]
```

```{r}
gmpd_panth_train <- as.data.frame(gmpd_panth_train)
gmpd_panth_test <- as.data.frame(gmpd_panth_test)
```


```{r initial model}
brt1 <- gbm.step(data = gmpd_panth_train, gbm.x = 4:45, gbm.y= 2,
                 family = "poisson", tree.complexity = 5,
                 learning.rate = 0.004, bag.fraction = 0.5)
```

```{r}
summary(brt1)
```
# Try again by parasite type

```{r}
gmpd_macro <- gmpd %>% filter(ParType %in% c("Arthropod", "Helminth")) %>% dplyr::select(HostCorrectedName,ParasiteCorrectedName) %>% 
  distinct() %>% 
  group_by(HostCorrectedName) %>% 
  summarize(psr=n())

gmpd_micro <- gmpd %>% filter(ParType %in% c("Bacteria", "Protozoa", "Virus")) %>% dplyr::select(HostCorrectedName,ParasiteCorrectedName) %>% 
  distinct() %>% 
  group_by(HostCorrectedName) %>% 
  summarize(psr=n())
```

```{r}
gmpd_panth_macro <- as.data.frame(gmpd_macro %>% inner_join(panth, by="HostCorrectedName"))
gmpd_panth_micro <- as.data.frame(gmpd_micro %>% inner_join(panth, by="HostCorrectedName"))
```

```{r}
brt2 <- gbm.step(data = gmpd_panth_macro, gbm.x = 4:45, gbm.y= 2,
                 family = "poisson", tree.complexity = 5,
                 learning.rate = 0.004, bag.fraction = 0.5)

brt3 <- gbm.step(data = gmpd_panth_micro, gbm.x = 4:45, gbm.y= 2,
                 family = "poisson", tree.complexity = 5,
                 learning.rate = 0.004, bag.fraction = 0.5)

```

```{r}
summary(brt2)
summary(brt3)
```
```{r}
gbm.plot(brt1, n.plots=5, plot.layout=c(2, 3), write.title = FALSE)
gbm.plot(brt2, n.plots=5, plot.layout=c(2, 3), write.title = FALSE)
gbm.plot(brt3, variable.no = 17, plot.layout=c(2, 3), write.title = FALSE)
```

```{r}
gbm.plot(brt1, variable.no = 17)
gbm.plot(brt2, variable.no = 17)
```




# Try with EltonTraits instead of Pantheria


```{r}
elton <- read_tsv(here("data", "eltontraits", "MamFuncDat.txt"))
```

```{r}
elton %<>% mutate(HostCorrectedName = Scientific)

elton %<>% dplyr::select(!c("ForStrat-Comment", "Diet-Source", "Diet-Certainty","ForStrat-Certainty", "ForStrat-Value",
                                 "Activity-Source", "Activity-Certainty", "BodyMass-Source"))

gmpd_elton <- as.data.frame(gmpd_PSR %>% inner_join(elton, by = "HostCorrectedName"))


#gmpd_elton$`ForStrat-Value` <- as.factor(gmpd_elton$`ForStrat-Value`)
```



```{r}
elton_brt_5_0.001 <- gbm.step(data = gmpd_elton, gbm.x = 6:21, gbm.y= 2,
                 family = "poisson", tree.complexity = 5,
                 learning.rate = 0.001, bag.fraction = 0.5)
```

```{r}
summary(elton_brt_5_0.001)
```

```{r}
#gbm.plot(elton_brt_5_0.001, variable.no = 1)
```


Try again with Elton, Pantheria, Amniote, and CLOVER

```{r}
amniote <- read_csv(here("data", "amniote", "ECOL_96_269/Data_Files/Amniote_Database_Aug_2015.csv")) #average value from amniote2's ranges

amniote[amniote == -999.00] <- NA

amniote %<>% select(-c(female_body_mass_at_maturity_g))

```


```{r}
amniote %<>% mutate(binomial = tolower(paste(genus, species, sep = " ")))
elton %<>% mutate(binomial = tolower(Scientific))
panth %<>% mutate(binomial = tolower(MSW_Binomial))

hosts <- amniote %>% left_join(., elton, by = "binomial")
hosts %<>% left_join(., panth, by = "binomial")
```

```{r, message = F}
mammals <- read_csv(here("data/clover/CLOVER_0.1_MammalViruses_AssociationsFlatFile.csv"))
viruses <- read_csv(here("data/clover/CLOVER_1.0_Viruses_AssociationsFlatFile.csv"))
helminths <- read_csv(here("data/clover/CLOVER_1.0_HelminthProtozoaFungi_AssociationsFlatFile.csv"))
bacteria <- read_csv(here("data/clover/CLOVER_1.0_Bacteria_AssociationsFlatFile.csv"))

colnames(mammals) <- gsub("Virus", "Pathogen", colnames(mammals))
mammals %<>% mutate(PathogenType = "virus")

clover <- rbind(mammals,viruses,bacteria,helminths)
```



```{r}
clover_psr <- clover %>% dplyr::select(Host,Pathogen) %>% 
                    distinct() %>% 
                    group_by(Host) %>% 
                    summarize(psr=n())
```

```{r}
clover_psr %<>% mutate(binomial = Host)

hosts_clover_psr <- hosts %>% left_join(., clover_psr, by = "binomial")

full_data <- hosts_clover_psr %>% filter(!is.na(psr))
```


```{r full data partition data}
train <- sample(1:nrow(full_data), nrow(full_data) / 2)
test <- full_data %>% mutate(row_num = rownames(.)) %>% filter(!row_num %in% train) %>% dplyr::select(row_num)
test <- as.integer(test$row_num)
full_data_train <- as.data.frame(full_data[train,])
full_data_test <- as.data.frame(full_data[test,])
```



```{r full data initial model}
brt_full <- gbm.step(data = full_data_train, gbm.x = c(8:35, 40:54, 57:98), gbm.y=101,
                 family = "poisson", tree.complexity = 5,
                 learning.rate = 0.004, bag.fraction = 0.5)
```

```{r}
summary(brt_full)
```

```{r}
#gbm.plot(brt_full)
```

