---
title: "BRT plots"
output: html_document
date: "2023-07-14"
---

```{r packages}
library(here)
library(tidyverse)
library(magrittr)

library(dismo)
library(gbm)
library(pdp)
library(cowplot)
library(RColorBrewer)
library(patchwork)
library(VennDiagram)
```

```{r theme}
theme_set(theme_minimal() +
            theme(title = element_text(size = 16),
                  axis.text.x = element_text(size = 12),
                  axis.text.y = element_text(size = 12)))
```

custom fill and color
```{r}
custom_fill <- scale_fill_manual(values = c("anthropogenic" = "blue",
                                            "behavior" = "pink",
                                            "morphology" = "red",
                                            "pace" = "orange",
                                            "environment" = "forestgreen",
                                            "other" = "#A93587",
                                            "metabolic" = "yellow",
                                            "taxonomy" = "#004D40",
                                            "ecology" = "#D81B60",
                                            "geography" = "#1E88E5",
                                            "host" = "#FFC107"))

custom_color <- scale_color_manual(values = c("anthropogenic" = "blue",
                                            "behavior" = "pink",
                                            "morphology" = "red",
                                            "pace" = "orange",
                                            "environment" = "forestgreen",
                                            "other" = "#A93587",
                                            "metabolic" = "yellow",
                                            "taxonomy" = "#004D40",
                                            "ecology" = "#D81B60",
                                            "geography" = "#1E88E5",
                                            "host" = "#FFC107"))

custom_par_fill <- scale_fill_manual(values = c("helminth" = "red",
                                                  "arthropod" = "blue",
                                                  "virus" = "forestgreen",
                                                  "bacteria" = "hotpink",
                                                  "protozoa" = "purple"))

```

```{r data}
#var_type <- read_csv(here("data/var_type.csv"))
var_type <- read_csv(here("data/var_type_alt.csv"))


brt1_elith_full <- readRDS(here("processed_data/brt_results/full_elith.rds"))
brt2_elith_helm <- readRDS(here("processed_data/brt_results/helm_elith.rds"))
brt3_elith_virus <- readRDS(here("processed_data/brt_results/virus_elith.rds"))
brt4_elith_arth <- readRDS(here("processed_data/brt_results/arth_elith.rds"))
brt5_elith_bact <- readRDS(here("processed_data/brt_results/bact_elith.rds"))
brt6_elith_proto <- readRDS(here("processed_data/brt_results/proto_elith.rds"))
brt7_elith_macro <- readRDS(here("processed_data/brt_results/macro_elith.rds"))
brt8_elith_micro <- readRDS(here("processed_data/brt_results/micro_elith.rds"))
```



```{r}
summary(brt1_elith_full)
summary(brt2_elith_helm)
summary(brt3_elith_virus)
summary(brt4_elith_arth)
summary(brt5_elith_bact)
summary(brt6_elith_proto)
summary(brt7_elith_macro)
summary(brt8_elith_micro)

```

```{r gmpd pdp 6}
gbm.plot(brt1_elith_full, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "full")
gbm.plot(brt2_elith_helm, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "helminth")
gbm.plot(brt3_elith_virus, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "virus")
gbm.plot(brt4_elith_arth, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "arthropod")
gbm.plot(brt5_elith_bact, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "bacteria")
gbm.plot(brt6_elith_proto, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "protozoa")
gbm.plot(brt7_elith_macro, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "macroparasites")
gbm.plot(brt8_elith_micro, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "microparasites")
```

```{r plot gbm test}
plot.gbm(brt1_elith_full, n.plots=6, plot.layout=c(2, 3), write.title = FALSE, common.scale = T, main = "full")

```

```{r plot longevity}
brt1_names <- brt1_elith_full$var.names
brt2_names <- brt2_elith_helm$var.names
brt3_names <- brt3_elith_virus$var.names
brt4_names <- brt4_elith_arth$var.names
brt5_names <- brt5_elith_bact$var.names
brt6_names <- brt6_elith_proto$var.names
brt7_names <- brt7_elith_macro$var.names
brt8_names <- brt8_elith_micro$var.names


brt1_long_plot_no <- which(brt1_names %in% c("MaxLongevity_m"))
brt2_long_plot_no <- which(brt2_names %in% c("MaxLongevity_m"))
brt3_long_plot_no <- which(brt3_names %in% c("MaxLongevity_m"))
brt4_long_plot_no <- which(brt4_names %in% c("MaxLongevity_m"))
brt5_long_plot_no <- which(brt5_names %in% c("MaxLongevity_m"))
brt6_long_plot_no <- which(brt6_names %in% c("MaxLongevity_m"))
brt7_long_plot_no <- which(brt7_names %in% c("MaxLongevity_m"))
brt8_long_plot_no <- which(brt8_names %in% c("MaxLongevity_m"))


gbm.plot(brt1_elith_full, variable.no = brt1_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "full")
gbm.plot(brt2_elith_helm, variable.no = brt2_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "helm")
gbm.plot(brt3_elith_virus, variable.no = brt3_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "virus")
gbm.plot(brt4_elith_arth, variable.no = brt4_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "arth")
gbm.plot(brt5_elith_bact, variable.no = brt5_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "bact")
gbm.plot(brt6_elith_proto, variable.no = brt6_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "proto")
gbm.plot(brt7_elith_macro, variable.no = brt7_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "macro")
gbm.plot(brt8_elith_micro, variable.no = brt8_long_plot_no, plot.layout=c(1, 1), write.title = FALSE, main = "micro")

```

```{r plot gbm longevity}
plot.gbm(brt1_elith_full, n.plots=6, i.var = brt1_long_plot_no, main = "full", type = "response")
plot.gbm(brt2_elith_helm, n.plots=6, i.var = brt2_long_plot_no, main = "helminth", type = "response")
plot.gbm(brt3_elith_virus, n.plots=6, i.var = brt3_long_plot_no, main = "virus", type = "response")
plot.gbm(brt4_elith_arth, n.plots=6, i.var = brt4_long_plot_no, main = "arthropod", type = "response")
plot.gbm(brt5_elith_bact, n.plots=6, i.var = brt5_long_plot_no, main = "bacteria", type = "response")
plot.gbm(brt6_elith_proto, n.plots=6, i.var = brt6_long_plot_no, main = "protozoa", type = "response")
plot.gbm(brt7_elith_macro, n.plots=6, i.var = brt7_long_plot_no, main = "macroparasites", type = "response")
plot.gbm(brt8_elith_micro, n.plots=6, i.var = brt8_long_plot_no, main = "microparasites", type = "response")
```


```{r relative importance}
brt1_full_ri <- brt1_elith_full$contributions
brt2_helm_ri <- brt2_elith_helm$contributions
brt3_virus_ri <- brt3_elith_virus$contributions
brt4_arth_ri <- brt4_elith_arth$contributions
brt5_bact_ri <- brt5_elith_bact$contributions
brt6_proto_ri <- brt6_elith_proto$contributions
brt7_macro_ri <- brt7_elith_macro$contributions
brt8_micro_ri <- brt8_elith_micro$contributions

```

```{r bind rows}
brt1_full_ri %<>% mutate(par_type = "full")
brt2_helm_ri %<>% mutate(par_type = "helminth")
brt3_virus_ri %<>% mutate(par_type = "virus")
brt4_arth_ri %<>% mutate(par_type = "arthropod")
brt5_bact_ri %<>% mutate(par_type = "bacteria")
brt6_proto_ri %<>% mutate(par_type = "protozoa")
brt7_macro_ri %<>% mutate(par_type = "macro")
brt8_micro_ri %<>% mutate(par_type = "micro")



brt_ri <- bind_rows(brt1_full_ri, brt2_helm_ri, brt3_virus_ri, brt4_arth_ri, brt5_bact_ri, brt6_proto_ri, brt7_macro_ri, brt8_micro_ri)
rownames(brt_ri) <- NULL
```


```{r make rel inf df}
brt_ri %<>% group_by(par_type) %>%
  arrange(desc(rel.inf)) %>%
  mutate(ranking = row_number())

var_type %<>% mutate(var = variable) %>% dplyr::select(-c(variable))

brt_ri %<>% left_join(., var_type)
```


```{r plot by variable}
brt_ri %>% filter(par_type != "full") %>%
ggplot(data = ., aes(x = par_type, y = ranking, group = var)) +
  geom_line(aes(color = var)) +
  geom_point(aes(color = var, alpha = 1), size = 4) +
  scale_y_reverse(breaks = 1:nrow(brt_ri))
```


```{r plot by type}
brt_ri %<>% mutate(top_fifteen = ifelse(ranking < 16, 1, 0))

subway <- brt_ri %>% filter(par_type %in% c("arthropod", "helminth", "bacteria", "protozoa", "virus")) %>%
filter(top_fifteen == T) %>%
  ggplot(data = ., aes(x = par_type, y = ranking, group = var, size = , shape = var)) +
    geom_line(aes(color = var_type), size = 1) +
    scale_shape_manual(values=1:nlevels(as.factor(brt_ri$var))) +
#    scale_color_discrete(type = getOption("ggplot2.discrete.colour")) + 
    geom_point(aes(color = var_type), size = 10) +
    scale_y_reverse(breaks = 1:nrow(brt_ri)) + 
    labs(x = "Parasite Type", 
         y = "Ranking",
         shape = "Variable",
         color = "Variable Type")+
    theme_minimal() +
  custom_color

```

```{r plot by macro micro}
brt_ri %>% filter(par_type %in% c("macro", "micro")) %>%
  filter(ranking < 11) %>%
  ggplot(data = ., aes(x = par_type, y = ranking, group = var, size = , shape = var)) +
    geom_line(aes(color = var_type), size = 1) +
    scale_shape_manual(values=1:nlevels(as.factor(brt_ri$var))) +
#    scale_color_discrete(type = getOption("ggplot2.discrete.colour")) + 
    geom_point(aes(color = var_type), size = 10) +
    scale_y_reverse(breaks = 1:nrow(brt_ri)) + 
    theme_minimal()
```
which variables are top 5 for each parasite type?

```{r}
arth_top <- 
  brt_ri %>% filter(par_type %in% c("arthropod")) %>% filter(ranking < 6) %>% 
  arrange((rel.inf)) %>%
  mutate(var=factor(var, levels=var)) %>%
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) + 
  geom_bar(position = "dodge", stat = "identity") +
  coord_flip()+
  ylim(0,17) +
  labs(title = "Arthropod Species Richness (RMSE = 8.4)",
       fill = "Variable Type") +
  xlab("Variable") + 
  ylab("")+
  custom_fill + 
  theme(legend.position = "none")

  
helm_top <-
  brt_ri %>% filter(par_type %in% c("helminth")) %>% filter(ranking < 6) %>% 
  arrange((rel.inf)) %>%
  mutate(var=factor(var, levels=var)) %>%
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) + 
  geom_bar(position = "dodge", stat = "identity") +
    coord_flip()+
  ylim(0,17) +
  labs(title = "Helminth Species Richness (RMSE = 36.1)",
       fill = "Variable Type") +
  xlab("Variable") + 
  ylab("Relative Influence (%)")+
  custom_fill + 
  theme(legend.position = "none")


virus_top <-
  brt_ri %>% filter(par_type %in% c("virus")) %>% filter(ranking < 6) %>% 
  arrange((rel.inf)) %>%
  mutate(var=factor(var, levels=var)) %>%
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) + 
  geom_bar(position = "dodge", stat = "identity",)+
    coord_flip()+
  ylim(0,27) +
  labs(title = "Virus Species Richness (RMSE = 4.9)",
       fill = "Variable Type") +
  xlab("") + 
  ylab("") +
  custom_fill + 
  theme(legend.position = "none")


bact_top <-
  brt_ri %>% filter(par_type %in% c("bacteria")) %>% filter(ranking < 6) %>% 
  arrange((rel.inf)) %>%
  mutate(var=factor(var, levels=var)) %>%
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) + 
  geom_bar(position = "dodge", stat = "identity") +
    coord_flip()+
  ylim(0,27) +
  labs(title = "Bacteria Species Richness (RMSE = 7.2)",
       fill = "Variable Type") +
  xlab("") + 
  ylab("") +
  custom_fill + 
  theme(legend.position = "none")


proto_top <-
  brt_ri %>% filter(par_type %in% c("protozoa")) %>% filter(ranking < 6) %>% 
  arrange((rel.inf)) %>%
  mutate(var=factor(var, levels=var)) %>%
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) + 
  geom_bar(position = "dodge", stat = "identity") +
    coord_flip()+
  ylim(0,27) +
  labs(title = "Protozoa Species Richness  (RMSE = 8.6)",
       fill = "Variable Type") +
  xlab("") + 
  ylab("Relative Influence (%)") +
  custom_fill + 
  theme(legend.position = "none")

top_all <- brt_ri %>% 
  ggplot(., aes(x = var, y = rel.inf, fill = var_type)) +
  geom_bar(stat = "identity") + custom_fill + labs(fill = "Variable Type")

top_5_ri <- arth_top / helm_top | bact_top / virus_top / proto_top

```




Which variables consistently rank in the top 15 among parasite types?
```{r}
top15 <- brt_ri %>% filter(ranking<16)
brt2_top15_helm <- top15 %>% filter(par_type == "helminth")
brt2_top15_helm <- brt2_top15_helm$var
brt3_top15_virus <- top15 %>% filter(par_type == "virus")
brt3_top15_virus <- brt3_top15_virus$var
brt4_top15_arth <- top15 %>% filter(par_type == "arthropod")
brt4_top15_arth <- brt4_top15_arth$var
brt5_top15_bact <- top15 %>% filter(par_type == "bacteria")
brt5_top15_bact <- brt5_top15_bact$var
brt6_top15_proto <- top15 %>% filter(par_type == "protozoa")
brt6_top15_proto <- brt6_top15_proto$var


intersect_vars <- Reduce(intersect, 
                          list(brt2_top15_helm, brt3_top15_virus, brt4_top15_arth, brt5_top15_bact, brt6_top15_proto))


#top_vars <- brt_ri %>% filter(var %in% intersect_vars)

brt_ri %<>% mutate(top_intersect = ifelse(var %in% intersect_vars, 1, 0))

```

```{r}
brt_ri %>% filter(top_intersect == T) %>% 
  filter(par_type %in% c("arthropod", "bacteria", "virus", "helminth", "protozoa")) %>%
  group_by(par_type) %>%
  ggplot(.,aes(x = par_type, y = rel.inf, fill = var)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  coord_flip()+
  labs(x = "Parasite Type",
       y = "Relative Influence",
       fill = "Variable")

brt_ri %>% filter(top_intersect == T) %>% 
  filter(par_type %in% c("arthropod", "bacteria", "virus", "helminth", "protozoa")) %>%
  filter(var != "ref_count") %>%
  group_by(var) %>%
  ggplot(.,aes(x = var, y = rel.inf, fill = par_type)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  custom_par_fill + 
  coord_flip()+
  labs(x = "Variable",
       y = "Relative Influence",
       fill = "Parasite Type")

```


```{r}
top_15_subway <- brt_ri %>% filter(par_type %in% c("arthropod", "helminth", "bacteria", "protozoa", "virus")) %>%
filter(top_fifteen == T) %>%
  ggplot(data = ., aes(x = par_type, y = ranking, group = var, size = , shape = var)) +
    geom_line(aes(color = as.logical(top_intersect)), size = 1) +
    scale_shape_manual(values=1:nlevels(as.factor(brt_ri$var))) +
#    scale_color_discrete(type = getOption("ggplot2.discrete.colour")) + 
    geom_point(aes(color = as.logical(top_intersect)), size = 10) +
    scale_y_reverse(breaks = 1:nrow(brt_ri)) + 
    labs(x = "Parasite Type", 
         y = "Ranking",
         shape = "Variable",
         color = "Variable Type")+
    theme_minimal() + 
  scale_color_manual(values = c("lightgrey","black")) +
  theme(legend.position = "none")

```



```{r make pdp function}
make_plots <- function(model, var, bin_n = 40, y_fixed = F, y_axis, par_type = 0) {
  
  data <- model$gbm.call$dataframe
  
  var_no <- which(colnames(data) %in% c(var))
  
  inv <- pdp::partial(model, n.trees=model$n.trees, var, prob = T, train = data, inv.link = exp, recursive = F)
  
  x_max <- max(data[var_no], na.rm=T)
  

  if(y_fixed==T){
    y_max = y_axis[2]
    y_min = y_axis[1]
  } else {
    y_max = max(inv$yhat)
    y_min <- min(inv$yhat)
  }
  
  if(par_type=="helminth"){
    col <- "red"
  }else if(par_type=="arthropod"){
    col <- "blue"
  }else if(par_type=="virus"){
    col <- "forestgreen"
  }else if(par_type=="bacteria"){
    col <- "hotpink"
  }else if(par_type=="protozoa"){
    col <- "purple"
  }else {
    col <- "black"
  }
  
  plot1 <- inv %>%
  na.omit() %>%
  ggplot() +
    geom_line(aes(x = .data[[var]], y = yhat),color=col,size=1) +
    xlim(0,x_max)+
    ylim(y_min,y_max)+
    ylab("PSR") +
    theme_minimal() +
    theme(axis.title.x = element_blank())+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
    theme(axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),axis.text=element_text(size=12))

  plot2 <- data %>%
  dplyr::select(.data[[var]]) %>%
  na.omit() %>%
  ggplot(aes(.data[[var]])) +
    geom_histogram(breaks = seq(0,x_max, x_max/bin_n), fill="gray") +
    #geom_histogram(fill="gray",binwidth=20) +
    scale_y_continuous(position = "right")+
    ylab("") +
    theme_minimal() +
    theme(axis.title.x = element_blank(),axis.text=element_text(size=12))#+
    #theme(plot.margin=unit(c(0,0,0,1.25),"cm"))
  
  plot1 <- add_sub(plot1,"")
  plot2 <- add_sub(plot2,var,size=12)
  
  list(pdp=plot1,histo=plot2)
}
```

```{r}
pdp_draw <- function(mod1,mod2,mod3,mod4,mod5, hist_x=0.05, pdp_x=-0.03, hist_scale=0.95, pdp_scale=0.975, pdp_y=0.05){
  ggdraw()+
  draw_plot(mod1$histo, x=hist_x, scale = hist_scale) +
  draw_plot(mod1$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod2$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod3$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod4$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y) +
  draw_plot(mod5$pdp, x=pdp_x, scale = pdp_scale, y = pdp_y)
  }
```


```{r make pdp plots}
max_long_y <- c(3,28)
brt1_plots_max_long <- make_plots(brt1_elith_full, "MaxLongevity_m")
brt2_plots_max_long <- make_plots(brt2_elith_helm, "MaxLongevity_m", y_fixed = T, y_axis = max_long_y, 
                                  par_type = "helminth")
brt3_plots_max_long <- make_plots(brt3_elith_virus, "MaxLongevity_m", y_fixed = T, y_axis = max_long_y, 
                                  par_type = "virus")
brt4_plots_max_long <- make_plots(brt4_elith_arth, "MaxLongevity_m", y_fixed = T, y_axis = max_long_y, 
                                  par_type = "arthropod")
brt5_plots_max_long <- make_plots(brt5_elith_bact, "MaxLongevity_m", y_fixed = T, y_axis = max_long_y, 
                                  par_type = "bacteria")
brt6_plots_max_long <- make_plots(brt6_elith_proto, "MaxLongevity_m", y_fixed = T, y_axis = max_long_y, 
                                  par_type = "protozoa")
```


```{r}
max_long_pdp <-pdp_draw(brt2_plots_max_long,
                 brt3_plots_max_long,
                 brt4_plots_max_long,
                 brt5_plots_max_long,
                 brt6_plots_max_long,
                 hist_x = ,
                 hist_scale = ,
                 pdp_x = -0.015,
                 pdp_scale = 0.98,
                 pdp_y =)

max_long_pdp

ggsave(here("figures/pdp/max_long.png"), max_long_pdp)
```


```{r ref count pdp}
ref_count_y <- c(1,35)

brt1_ref_count_plot <- make_plots(brt1_elith_full, "ref_count", y_fixed = T, y_axis = ref_count_y)
brt2_ref_count_plot <- make_plots(brt2_elith_helm, "ref_count", y_fixed = T, y_axis = ref_count_y, par_type = "helminth")
brt3_ref_count_plot <- make_plots(brt3_elith_virus, "ref_count", y_fixed = T, y_axis = ref_count_y, par_type = "virus")
brt4_ref_count_plot <- make_plots(brt4_elith_arth, "ref_count", y_fixed = T, y_axis = ref_count_y, par_type = "arthropod")
brt5_ref_count_plot <- make_plots(brt5_elith_bact, "ref_count", y_fixed = T, y_axis = ref_count_y, par_type = "bacteria")
brt6_ref_count_plot <- make_plots(brt6_elith_proto, "ref_count", y_fixed = T, y_axis = ref_count_y, par_type = "protozoa")
brt7_ref_count_plot <- make_plots(brt7_elith_macro, "ref_count", y_fixed = T, y_axis = ref_count_y)
brt8_ref_count_plot <- make_plots(brt8_elith_micro, "ref_count", y_fixed = T, y_axis = ref_count_y)
```

```{r}
ref_count_pdp <- pdp_draw(brt2_ref_count_plot,
                     brt3_ref_count_plot,
                     brt4_ref_count_plot,
                     brt5_ref_count_plot,
                     brt6_ref_count_plot,
                     hist_x = ,
                     hist_scale = ,
                     pdp_x = -0.013,
                     pdp_scale = 0.95,
                     pdp_y = 0.055)

ref_count_pdp

ggsave(here("figures/pdp/ref_count.png"), ref_count_pdp)

```

```{r}
maturity_y <- c(5,32)

brt2_maturity_plot <- make_plots(brt2_elith_helm, 
                                 "SexualMaturityAge_d", y_fixed = T, y_axis = maturity_y, par_type = "helminth")
brt3_maturity_plot <- make_plots(brt3_elith_virus, 
                                 "SexualMaturityAge_d", y_fixed = T, y_axis = maturity_y, par_type = "virus")
brt4_maturity_plot <- make_plots(brt4_elith_arth, 
                                 "SexualMaturityAge_d", y_fixed = T, y_axis = maturity_y, par_type = "arthropod")
brt5_maturity_plot <- make_plots(brt5_elith_bact, 
                                 "SexualMaturityAge_d", y_fixed = T, y_axis = maturity_y, par_type = "bacteria")
brt6_maturity_plot <- make_plots(brt6_elith_proto, 
                                 "SexualMaturityAge_d", y_fixed = T, y_axis = maturity_y, par_type = "protozoa")

```


```{r}
maturity_pdp <- pdp_draw(brt2_maturity_plot,
                     brt3_maturity_plot,
                     brt4_maturity_plot,
                     brt5_maturity_plot,
                     brt6_maturity_plot,
                     hist_x = ,
                     hist_scale = ,
                     pdp_x = -0.029,
                     pdp_scale = 0.951,
                     pdp_y = )

maturity_pdp

ggsave(here("figures/pdp/sexual_maturity.png"), maturity_pdp)

```

```{r}
range_y <- c(5,30)

brt2_range_plot <- make_plots(brt2_elith_helm, 
                                 "HomeRange_km", y_fixed = T, y_axis = range_y, par_type = "helminth")
brt3_range_plot <- make_plots(brt3_elith_virus, 
                                 "HomeRange_km", y_fixed = T, y_axis = range_y, par_type = "virus")
brt4_range_plot <- make_plots(brt4_elith_arth, 
                                 "HomeRange_km", y_fixed = T, y_axis = range_y, par_type = "arthropod")
brt5_range_plot <- make_plots(brt5_elith_bact, 
                                 "HomeRange_km", y_fixed = T, y_axis = range_y, par_type = "bacteria")
brt6_range_plot <- make_plots(brt6_elith_proto, 
                                 "HomeRange_km", y_fixed = T, y_axis = range_y, par_type = "protozoa")

```


```{r}
range_pdp <- pdp_draw(brt2_range_plot,
                     brt3_range_plot,
                     brt4_range_plot,
                     brt5_range_plot,
                     brt6_range_plot,
                     hist_x = ,
                     hist_scale = ,
                     pdp_x = -0.01,
                     pdp_scale = 0.945,
                     pdp_y = )

range_pdp

ggsave(here("figures/pdp/home_range.png"), range_pdp)

```

```{r}
area_y <- c(5,26)

brt2_area_plot <- make_plots(brt2_elith_helm, 
                                 "GR_Area_km", y_fixed = T, y_axis = area_y, par_type = "helminth")
brt3_area_plot <- make_plots(brt3_elith_virus, 
                                 "GR_Area_km", y_fixed = T, y_axis = area_y, par_type = "virus")
brt4_area_plot <- make_plots(brt4_elith_arth, 
                                 "GR_Area_km", y_fixed = T, y_axis = area_y, par_type = "arthropod")
brt5_area_plot <- make_plots(brt5_elith_bact, 
                                 "GR_Area_km", y_fixed = T, y_axis = area_y, par_type = "bacteria")
brt6_area_plot <- make_plots(brt6_elith_proto, 
                                 "GR_Area_km", y_fixed = T, y_axis = area_y, par_type = "protozoa")

```


```{r}
area_pdp <- pdp_draw(brt2_area_plot,
                     brt3_area_plot,
                     brt4_area_plot,
                     brt5_area_plot,
                     brt6_area_plot,
                     hist_x = ,
                     hist_scale = ,
                     pdp_x = -0.01,
                     pdp_scale = 0.95,
                     pdp_y = )

area_pdp

ggsave(here("figures/pdp/gr_area.png"), area_pdp)

```

```{r}
pop_dens_y <- c(5,30)

brt2_pop_dens_plot <- make_plots(brt2_elith_helm, 
                                 "HuPopDen_Mean_n_km", y_fixed = T, y_axis = pop_dens_y, par_type = "helminth")
brt3_pop_dens_plot <- make_plots(brt3_elith_virus, 
                                 "HuPopDen_Mean_n_km", y_fixed = T, y_axis = pop_dens_y, par_type = "virus")
brt4_pop_dens_plot <- make_plots(brt4_elith_arth, 
                                 "HuPopDen_Mean_n_km", y_fixed = T, y_axis = pop_dens_y, par_type = "arthropod")
brt5_pop_dens_plot <- make_plots(brt5_elith_bact, 
                                 "HuPopDen_Mean_n_km", y_fixed = T, y_axis = pop_dens_y, par_type = "bacteria")
brt6_pop_dens_plot <- make_plots(brt6_elith_proto, 
                                 "HuPopDen_Mean_n_km", y_fixed = T, y_axis = pop_dens_y, par_type = "protozoa")

```


```{r}
pop_dens_pdp <- pdp_draw(brt2_pop_dens_plot,
                     brt3_pop_dens_plot,
                     brt4_pop_dens_plot,
                     brt5_pop_dens_plot,
                     brt6_pop_dens_plot,
                     hist_x = ,
                     hist_scale = ,
                     pdp_x = -0.01,
                     pdp_scale = 0.95,
                     pdp_y = )

pop_dens_pdp

ggsave(here("figures/pdp/pop_dens.png"), pop_dens_pdp)

```

```{r}
legend <- tibble(par_type = c("Arthropod", "Helminth", "Bacteria", "Virus", "Protozoa"),
                 x_val = c(1:5),
                 y_val = c(1:5))

ggplot(legend, aes(x = x_val, y = y_val, color = par_type)) + geom_line(size = 2) + 
  scale_color_manual(values = c("blue", "hotpink", "red", "purple", "forestgreen")) + labs(color = "Parasite Type")

```




