---
title: "databases"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

Overview of each database


```{r packages, message = F}
library(here)
library(tidyverse)
library(magrittr)
```

```{r functions}
makeMissing <- function(df) {
  tibble(col = names(colSums(is.na(df))), missing = as.numeric(colSums(is.na(df))))
}

plotMissing <- function(df) {
  df %>% arrange(missing) %>% 
  mutate(col=factor(col, levels=col)) %>% 
  ggplot(.,aes(x=col,y=missing)) + 
    geom_col() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(title = deparse(substitute(df)))
}
```

```{r setTheme}
theme_set(theme_bw())
```


# Amniote

```{r readAmniote}
amniote <- read_csv(here("data", "amniote", "ECOL_96_269/Data_Files/Amniote_Database_Aug_2015.csv")) #average value from amniote2's ranges
#amniote1 <- read_csv(here("data", "amniote", "ECOL_96_269/Data_Files/Amniote_Range_Count_Aug_2015.csv")) #ranges taken from amniote2's sources
#amniote2 <- read_csv(here("data", "amniote", "ECOL_96_269/Data_Files/Amniote_Sparse_Table_Aug_2015.csv")) #all sources and observations
```

```{r exploreAmniote}
amn_mamm <- amniote %>% filter(class == "Mammalia")
amn_mamm[amn_mamm==-999] <- NA

amn_missing <- makeMissing(amn_mamm)

plotMissing(amn_missing)
```

# AnimalTraits

```{r readAnimalTraits}
animal <- read_csv(here("data", "animaltraits", "observations.csv"))
```

```{r exploreAnimalTraits}
ani_mamm <- animal %>% filter(class == "Mammalia")

ani_missing <- makeMissing(ani_mamm)

plotMissing(ani_missing)
```

# EltonTraits

```{r readElton}
elton <- read_tsv(here("data", "eltontraits", "MamFuncDat.txt"))
```

```{r exploreElton}
elton_missing <- makeMissing(elton)

plotMissing(elton_missing)
```

# HormoneBase

```{r readHormone}
hormone <- read_csv(here("data", "hormonebase", "HormoneBase_v1.csv"))
```

```{r exploreHormone}
horm_mamm <- hormone %>% filter(Vert_Group == "Mammal")

horm_missing <- makeMissing(horm_mamm)

plotMissing(horm_missing)
```

# Pantheria

```{r}
panth1 <- read_tsv(here("data", "pantheria", "ECOL_90_184/PanTHERIA_1-0_WR05_Aug2008.txt"))
#panth2 <- read_tsv(here("data", "pantheria", "ECOL_90_184/PanTHERIA_1-0_WR93_Aug2008.txt"))
```

There are two pantheria files that are slightly different. I assume WR05 stands for 2005 and is the most up-to-date version so I will use that.

# ```{r}
# panth1_names <- panth1$MSW05_Binomial
# panth2_names <- panth2$MSW93_Binomial
# 
# panth2_subset <- panth2[which(panth2_names %in% panth1_names),]
# panth2_out <- panth2[which(!(panth2_names %in% panth1_names)),]
# ```

```{r}
panth1 %<>% rename_with(~ gsub("MSW05_","", .x, fixed = T))
#panth2 %<>% rename_with(~ gsub("MSW93_","", .x, fixed = T))

#panth1 %<>% rename_with(~ gsub("14-1_InterbirthInterval_d", "14-1_InterBirthInterval_d", .x, fixed = T))

#panth1 %<>% rename_with(~ gsub("26-4_GR_MidRangeLat_dd", "26-4_GR_MRLat_dd", .x, fixed = T))

#panth1 %<>% rename_with(~ gsub("26-7_GR_MidRangeLong_dd", "26-7_GR_MRLong_dd", .x, fixed = T))

#panth <- rbind(panth1, panth2)

```


```{r}
panth_missing <- makeMissing(panth1)

plotMissing(panth_missing)
```


