---
title: "life history"
author: "Daniel Suh"
date: "1/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = F}
library(tidyverse)
library(magrittr)
library(here)
```

```{r, message =F}
becker_han <- read_csv(here("data/Becker Han 2020 GEB_gpf & BRT data.csv"))
healy_axis <- read_csv(here("data/healy_axis_analysis.csv"))
healy_host <- read_csv(here("data/healy_host_par.csv"))
```

get parasite species richness from healy_host_par.csv
```{r}
healy_psr <- healy_host %>% dplyr::select(host, parasite) %>% group_by(host) %>% summarize(n=n())
```

join with life history data from healy_axis_analysis.csv
first some string manipulation
```{r}
healy_axis %<>% mutate(host = gsub("_", " ", healy_axis$species))
healy_axis_psr <- left_join(healy_axis, healy_psr, by = "host")

#average over duplicates
healy_axis_psr_avg <- healy_axis_psr %>% group_by(species) %>% mutate_each(funs(mean), c(2:15,17,18,20,24)) %>% distinct()

healy_axis_psr_avg$mode_of_life <- factor(healy_axis_psr_avg$mode_of_life)
healy_axis_psr_avg$IUCN <- factor(healy_axis_psr_avg$IUCN)
healy_axis_psr_avg$met_type <- factor(healy_axis_psr_avg$met_type)

healy_axis_psr_avg %<>% select(-c(taxa_name,animal,host))
```

mock pca - dont trust this. just checking out workflow
```{r}
healy_pca <- healy_axis_psr_avg %>% select(-c(mode_of_life,IUCN,met_type,repo_output,met_rate,n,mass_g,mean_repo_rate)) %>% column_to_rownames(.,var="species")
healy_pca_results <- prcomp(healy_pca)
pc1_scores <- enframe(healy_pca_results$x[,1], name = "species", value = "pc1")
tmp <- healy_axis_psr_avg %>% select(species, n)
pc1_scores %<>% left_join(.,tmp, by = "species")
pc1_scores %>% ggplot(.,aes(x=pc1,y=log10(n))) + geom_point()
```


mock gbm
```{r}
library(gbm)
```

